### ISSUE TITLE
userAgent issue with FunCaptcha solve method

### ISSUE THREAD

**Issue by KernelPanic0** [anti-captcha/anticaptcha-go#1]
Hello,
There is an issue with your SolveFunCaptchaProxyOn. SolveFunCaptcha methods and the FunCaptcha struct. When I use your library for solving funcaptcha challenges I get back a response stating that the userAgent header is missing. I fixed this by simply adding 	UserAgent        string to the FunCaptcha struct, and adding the userAgent header to the previously mentioned methods. Please make these changes!

**Comment by anti-captcha** [comment]
Hi, fixed it on API level. userAgent is now not required.
